### ISSUE TITLE
./getthemall.sh: line 30: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by bardware** [memefulsearch/memefulsearch.github.io#8]
Hi,

I cloned your repo and called `./getthemall.sh` in the `bin` directory.
I get the error message `./getthemall.sh: line 30: syntax error: unexpected end of file`.  How do I have to call this script to get all the files? Do I need a certain shell?

Best,
Bernhard

**Comment by mauricioprado00** [comment]
if you are trying to obtain the data, you could just parse the file data.js. it has the updated data of all meme images up to today.

**Comment by mauricioprado00** [comment]
I am not sure why you are getting that error. it suppose to work either with bash or sh.
Maybe you are running it with another shell? zsh or something else?

**Comment by mauricioprado00** [comment]
@bardware so, did you figured it out?

**Comment by bardware** [comment]
Sorry for not returning earlier.
I Originally I had tried to run the sh file in a WSL environment which I believe to be a Ubuntu bash.
In the meantime I tried in a different shell (MSYS2 under Windows) and it indeed worked. 👍 

Thanks for the follow up.
