### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by bardware** [memefulsearch/memefulsearch.github.io#9]
I just wanted to search a GIF on the website and see nothing. In the Browser's developer console I see CORS errors and something with  `"sha384"-Hashes im "integrity"-Attribut`

**Comment by mauricioprado00** [comment]
@bardware I cant reproduce this. Could you give more information? what browser are you using? what did you type on the search? can you copy the whole debug information?

**Comment by bardware** [comment]
Thanks for the reply.
At the moment I would guess, that the error wasn't on your side.
I didn't paste the whole console log, because it was written in German language.
I'm on Firefox 77.0.1 and it seems it was not possible to load the jQuery library. It works now, for me too, so the error may have been on jQuery's side.

**Comment by mauricioprado00** [comment]
@bardware du könntest auch es auf Deutsch schrieben.
Anyways, I am glad to hear it works. Glad also to hear people use the tool.
